### ISSUE TITLE
Problem with options >5

### ISSUE THREAD

**Issue by barup** [rtrouton/payload-free_package_printer_generator#1]
Great script, but I had problems with some printer queues with more than 5 options.
I changes the following:
if [[ "${option_6}" != "" ]]; then
    add_option6="-o \"${option_6}\" "
fi

if [[ "${option_7}" != "" ]]; then
    add_option7="-o \"${option_7}\" "
fi

if [[ "${option_8}" != "" ]]; then
    add_option8="-o \"${option_8}\" "
fi

if [[ "${option_9}" != "" ]]; then
    add_option9="-o \"${option_9}\" "
fi

before it said add_option5 in these five places.

**Comment by rtrouton** [comment]
Can you post a sanitized version of the command you used? I want to see if I can reproduce the problem.

**Comment by barup** [comment]
I've remove the signing option from the command, but this command doesn't set option 6,7 and 8.
I looked at your script, and the add_option5 is set multiple times. I guess it could be a copy paste error after expanding the script to accept 9 options instead of 5.

sudo ./payload-free_package_printer_generator.sh -n "A4-sh" -l "Labland printerrum" -d "Labland A4 SortHvid" -a "lpd://192.168.0.50" -p "/Library/Printers/PPDs/Contents/Resources/GENERIC25C-9.gz" -1 "PaperSources=PC210" -2 "PageSize=A4JIS" -3 "KMDuplex=Single" -4 "KMInputSlot=Auto" -5 "MediaType=Plain" -6 "SelectColor=Grayscale" -7 "ColorModel=Gray" -8 "SimulationProfile=None"

**Comment by rtrouton** [comment]
You may want to use the current revision of the script, as I'm not able to duplicate the issue you're seeing. 

The current script gives me this output:

> computername:~ rtrouton$ cd /Users/rtrouton/Desktop/payload-free_package_printer_generator
> computername:payload-free_package_printer_generator rtrouton$ sudo ./payload-free_package_printer_generator.sh -n "A4-sh" -l "Labland printerrum" -d "Labland A4 SortHvid" -a "lpd://192.168.0.50" -p "/Library/Printers/PPDs/Contents/Resources/GENERIC25C-9.gz" -1 "PaperSources=PC210" -2 "PageSize=A4JIS" -3 "KMDuplex=Single" -4 "KMInputSlot=Auto" -5 "MediaType=Plain" -6 "SelectColor=Grayscale" -7 "ColorModel=Gray" -8 "SimulationProfile=None"
> Password:
> 
> You have chosen the following printer configuration options:
> 
> Printer Queue Name:  A4-sh
> Printer Location:  Labland printerrum
> Printer Display Name:  Labland A4 SortHvid
> Printer Address:  lpd://192.168.0.50
> Printer Driver:  /Library/Printers/PPDs/Contents/Resources/GENERIC25C-9.gz
> Additional Printer Option:  PaperSources=PC210
> Additional Printer Option:  PageSize=A4JIS
> Additional Printer Option:  KMDuplex=Single
> Additional Printer Option:  KMInputSlot=Auto
> Additional Printer Option:  MediaType=Plain
> Additional Printer Option:  SelectColor=Grayscale
> Additional Printer Option:  ColorModel=Gray
> Additional Printer Option:  SimulationProfile=None
> Printer Sharing:  Disabled
> 
> pkgbuild: Inferring bundle components from contents of /tmp/A4-sh/nopayload
> pkgbuild: Adding top-level postinstall script
> pkgbuild: Wrote package to /tmp/A4-sh/Create Labland A4 SortHvid Printer.pkg
> computername:payload-free_package_printer_generator rtrouton$



The following `postinstall` script is generated:


`#!/bin/bash`

`# This payload-free package will configure a printer with the following options:`

`# Printer Queue Name:  A4-sh`
`# Printer Location:  Labland printerrum`
`# Printer Display Name:  Labland A4 SortHvid`
`# Printer Address:  lpd://192.168.0.50`
`# Printer Driver:  /Library/Printers/PPDs/Contents/Resources/GENERIC25C-9.gz`
`# Additional Printer Option:  PaperSources=PC210`
`# Additional Printer Option:  PageSize=A4JIS`

`# Additional Printer Option:  KMDuplex=Single`
`# Additional Printer Option:  KMInputSlot=Auto`
`# Additional Printer Option:  MediaType=Plain`
`# Additional Printer Option:  SelectColor=Grayscale`
`# Additional Printer Option:  ColorModel=Gray`
`# Additional Printer Option:  SimulationProfile=None`

`# Printer Sharing:  Disabled`

`# Remove existing printer queue if one exists.`

`/usr/sbin/lpadmin -x A4-sh`

`# Add new printer queue with the specified options`

`/usr/sbin/lpadmin -p "A4-sh" -L "Labland printerrum" -D "Labland A4 SortHvid" -v "lpd://192.168.0.50" -P "/Library/Printers/PPDs/Contents/Resources/GENERIC25C-9.gz" -o "printer-is-shared=false" -o "PaperSources=PC210" -o "PageSize=A4JIS" -o "KMDuplex=Single" -o "KMInputSlot=Auto" -o "SimulationProfile=None" -E`

**Comment by barup** [comment]
if you look at the lpadmin command at the end, it's missing the SelectColor and ColorModel option.

**Comment by barup** [comment]
I can send you my modified version of the script ?

**Comment by rtrouton** [comment]
Now I see it, this section was wrong (I was looking in the wrong spot.) Please try again with the latest script.

```
if [[ "${option_5}" != "" ]]; then
    add_option5="-o \"${option_5}\" "
fi

if [[ "${option_6}" != "" ]]; then
    add_option6="-o \"${option_6}\" "
fi

if [[ "${option_7}" != "" ]]; then
    add_option7="-o \"${option_7}\" "
fi

if [[ "${option_8}" != "" ]]; then
    add_option8="-o \"${option_8}\" "
fi

if [[ "${option_9}" != "" ]]; then
    add_option9="-o \"${option_9}\" "
fi
```

**Comment by barup** [comment]
Yes, new version fixed the issue.
